export const APP_NAVIGATOR = 'APP_NAVIGATOR'
export const AUTH_NAVIGATOR = 'AUTH_NAVIGATOR'
export const BOTTOM_TAB_NAVIGATOR = 'BOTTOM_TAB_NAVIGATOR'
export const FILTER_NAVIGATOR = 'FILTER_NAVIGATOR'
export const SETTINGS_NAVIGATOR = 'SETTINGS_NAVIGATOR'
export const ONBOARDING_NAVIGATOR = 'ONBOARDING_NAVIGATOR'
export const MATCH_NAVIGATOR = 'MATCH_NAVIGATOR'
export const COMPETITION_NAVIGATOR = 'COMPETITION_NAVIGATOR'

export default {
  APP_NAVIGATOR,
  AUTH_NAVIGATOR,
  BOTTOM_TAB_NAVIGATOR,
  FILTER_NAVIGATOR,
  SETTINGS_NAVIGATOR,
  ONBOARDING_NAVIGATOR,
  MATCH_NAVIGATOR,
  COMPETITION_NAVIGATOR
}
