export const PROFILE_SCREEN = 'PROFILE_SCREEN'
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN'
export const LOGIN_WITH_EMAIL_SCREEN = 'LOGIN_WITH_EMAIL_SCREEN'
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN'
export const SIGN_UP_WITH_EMAIL_SCREEN = 'SIGN_UP_WITH_EMAIL_SCREEN'
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN'
export const ONBOARDING_FIRST_SCREEN = 'ONBOARDING_FIRST_SCREEN'
export const ONBOARDING_SECOND_SCREEN = 'ONBOARDING_SECOND_SCREEN'
export const ONBOARDING_THIRD_SCREEN = 'ONBOARDING_THIRD_SCREEN'
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN'
export const LANGUAGES_ALL_SCREEN = 'LANGUAGES_ALL_SCREEN'
export const IMAGE_UPLOAD_SCREEN = 'IMAGE_UPLOAD_SCREEN'
export const MATCHES_ALL_SCREEN = 'MATCHES_ALL_SCREEN'
export const MATCH_FILTER_SCREEN = 'MATCH_FILTER_SCREEN'
export const COMPETITIONS_ALL_SCREEN = 'COMPETITIONS_ALL_SCREEN'
export const COMPETITION_FILTER_SCREEN = 'COMPETITION_FILTER_SCREEN'
export const MATCH_SHOW_SCREEN = 'MATCH_SHOW_SCREEN'
export const MATCH_TEAMS_SHOW_SCREEN = 'MATCH_TEAMS_SHOW_SCREEN'
export const COMPETITION_SHOW_SCREEN = 'COMPETITION_SHOW_SCREEN'
export const COMPETITION_TEAMS_SHOW_SCREEN = 'COMPETITION_TEAMS_SHOW_SCREEN'
export const COMPETITION_MATCHES_SHOW_SCREEN = 'COMPETITION_MATCHES_SHOW_SCREEN'
export const COMPETITION_VIDEO_GAME_SHOW_SCREEN =
  'COMPETITION_VIDEO_GAME_SHOW_SCREEN'

export default {
  PROFILE_SCREEN,
  FORGOT_PASSWORD_SCREEN,
  LOGIN_WITH_EMAIL_SCREEN,
  SIGN_IN_SCREEN,
  SIGN_UP_WITH_EMAIL_SCREEN,
  DASHBOARD_SCREEN,
  ONBOARDING_FIRST_SCREEN,
  ONBOARDING_SECOND_SCREEN,
  ONBOARDING_THIRD_SCREEN,
  SETTINGS_SCREEN,
  LANGUAGES_ALL_SCREEN,
  IMAGE_UPLOAD_SCREEN
}
