export const PROFILE_SCREEN = 'PROFILE_SCREEN'
export const FORGOT_PASSWORD_SCREEN = 'FORGOT_PASSWORD_SCREEN'
export const LOGIN_WITH_EMAIL_SCREEN = 'LOGIN_WITH_EMAIL_SCREEN'
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN'
export const SIGN_UP_WITH_EMAIL_SCREEN = 'SIGN_UP_WITH_EMAIL_SCREEN'
export const DASHBOARD_SCREEN = 'DASHBOARD_SCREEN'
export const ONBOARDING_FIRST_SCREEN = 'ONBOARDING_FIRST_SCREEN'
export const ONBOARDING_SECOND_SCREEN = 'ONBOARDING_SECOND_SCREEN'
export const ONBOARDING_THIRD_SCREEN = 'ONBOARDING_THIRD_SCREEN'
export const SETTINGS_SCREEN = 'SETTINGS_SCREEN'
export const LANGUAGES_ALL = 'LANGUAGES_ALL'
export const IMAGE_UPLOAD_SCREEN = 'IMAGE_UPLOAD_SCREEN'

export default {
  PROFILE_SCREEN,
  FORGOT_PASSWORD_SCREEN,
  LOGIN_WITH_EMAIL_SCREEN,
  SIGN_IN_SCREEN,
  SIGN_UP_WITH_EMAIL_SCREEN,
  DASHBOARD_SCREEN,
  ONBOARDING_FIRST_SCREEN,
  ONBOARDING_SECOND_SCREEN,
  ONBOARDING_THIRD_SCREEN,
  SETTINGS_SCREEN,
  LANGUAGES_ALL,
  IMAGE_UPLOAD_SCREEN
}
